# Generated by Django 4.2.6 on 2023-10-24 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint_box', '0002_complaint_box_complaint'),
    ]

    operations = [
        migrations.CreateModel(
            name='complaint_box_acknowledgement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('ackmesg', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='complaint_box_faculty',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('designation', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200, unique=True)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='complaint_box_faculty_acknowledgement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('ackmesg', models.CharField(max_length=200)),
            ],
        ),
    ]
