# Generated by Django 4.2.6 on 2023-10-27 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint_box', '0005_alter_complaint_box_register_userimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint_box_register',
            name='useremail',
            field=models.CharField(default=True, max_length=200),
        ),
    ]
