# Generated by Django 4.2.6 on 2023-10-29 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint_box', '0006_alter_complaint_box_register_useremail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint_box_complaint',
            name='complaintmessage',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='complaint_box_complaint',
            name='complaintto',
            field=models.CharField(choices=[('Trainer', 'Trainer'), ('HR', 'HR'), ('Operation Head', 'Operation Head')], max_length=200),
        ),
    ]
