# Generated by Django 4.2.6 on 2023-10-29 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint_box', '0007_alter_complaint_box_complaint_complaintmessage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint_box_complaint',
            name='complaintmessage',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='complaint_box_complaint',
            name='complaintto',
            field=models.CharField(max_length=200),
        ),
    ]
