# Generated by Django 4.2.6 on 2023-11-13 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaint_box', '0008_alter_complaint_box_complaint_complaintmessage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint_box_acknowledgement',
            old_name='ackmesg',
            new_name='acknowledgement_message',
        ),
        migrations.RenameField(
            model_name='complaint_box_faculty_acknowledgement',
            old_name='ackmesg',
            new_name='acknowledgement_message',
        ),
    ]
